### ISSUE TITLE
double free or corruption in SU2_CFD

### ISSUE THREAD

**Issue by kunstrasenspringer** [precice/su2-adapter#3]
Hi,
I'm trying to realize the tutorial [https://github.com/precice/precice/wiki/FSI-tutorial](url) within a dockerimage. 
I could build the software without big fuzz. 
When I want to simulate and run the command:

_ccx_preCICE -i flap -precice-participant Calculix & **SU2_CFD euler_config_coupled.cfg**_

the simulation finishes with a _double free or corruption error_. So it returns a _non-zero code_ in docker and I can not continue building the image. Can you help me?

Error message:

```
Process #0/0: Done finalizing preCICE!
*** Error in SU2_CFD': double free or corruption (fasttop): 0x00000000031b7f30 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f2a88f267e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f2a88f2f37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f2a88f3353c]
SU2_CFD[0x4ce37b]
SU2_CFD[0x42b0f3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f2a88ecf830]
SU2_CFD[0x42a969]
======= Memory map: ========
00400000-0118a000 r-xp 00000000 08:06 944100                             /home/alice/su2-bin/bin/SU2_CFD
01389000-013ba000 r--p 00d89000 08:06 944100                             /home/alice/su2-bin/bin/SU2_CFD
013ba000-013bc000 rw-p 00dba000 08:06 944100                             /home/alice/su2-bin/bin/SU2_CFD
013bc000-01436000 rw-p 00000000 00:00 0 
02993000-03570000 rw-p 00000000 00:00 0                                  [heap]
7f2a74000000-7f2a74021000 rw-p 00000000 00:00 0 
7f2a74021000-7f2a78000000 ---p 00000000 00:00 0 
7f2a78e38000-7f2a78e39000 ---p 00000000 00:00 0 
7f2a78e39000-7f2a79639000 rw-p 00000000 00:00 0 
7f2a79639000-7f2a7964e000 r-xp 00000000 08:06 292956                     /usr/lib/openmpi/lib/openmpi/mca_osc_pt2pt.so
.... 
Job finished
The command '/bin/sh -c ccx_preCICE -i flap -precice-participant Calculix & SU2_CFD euler_config_coupled.cfg' returned a non-zero code: 255

```

**Comment by arusch** [comment]
Hi,

I haven’t yet tested dockers but I will investigate the problem. Would you please tell me, which versions of SU2, CalculiX and preCICE you use? Also, please confirm that the adapter versions, indeed, correspond to the SU2 und CalculiX versions that you use.
Also, what OS are you running?

Best regards
Alexander

Am 13.03.2018 um 15:37 schrieb kunstrasenspringer <notifications@github.com<mailto:notifications@github.com>>:


Hi,
I'm trying to realize the tutorial https://github.com/precice/precice/wiki/FSI-tutorial<url> within a dockerimage.
I could build the software without big fuzz.
When I want to simulate and run the command:

ccx_preCICE -i flap -precice-participant Calculix & SU2_CFD euler_config_coupled.cfg

the simulation finishes with a double free or corruption error. So it returns a non-zero code in docker and I can not continue building the image. Can you help me?

Error message:

Process #0/0: Done finalizing preCICE!
*** Error in SU2_CFD': double free or corruption (fasttop): 0x00000000031b7f30 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f2a88f267e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f2a88f2f37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f2a88f3353c]
SU2_CFD[0x4ce37b]
SU2_CFD[0x42b0f3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f2a88ecf830]
SU2_CFD[0x42a969]
======= Memory map: ========
00400000-0118a000 r-xp 00000000 08:06 944100 /home/alice/su2-bin/bin/SU2_CFD
01389000-013ba000 r--p 00d89000 08:06 944100 /home/alice/su2-bin/bin/SU2_CFD
013ba000-013bc000 rw-p 00dba000 08:06 944100 /home/alice/su2-bin/bin/SU2_CFD
013bc000-01436000 rw-p 00000000 00:00 0
02993000-03570000 rw-p 00000000 00:00 0 [heap]
7f2a74000000-7f2a74021000 rw-p 00000000 00:00 0
7f2a74021000-7f2a78000000 ---p 00000000 00:00 0
7f2a78e38000-7f2a78e39000 ---p 00000000 00:00 0
7f2a78e39000-7f2a79639000 rw-p 00000000 00:00 0
7f2a79639000-7f2a7964e000 r-xp 00000000 08:06 292956 /usr/lib/openmpi/lib/openmpi/mca_osc_pt2pt.so
....
Job finished
The command '/bin/sh -c ccx_preCICE -i flap -precice-participant Calculix & SU2_CFD euler_config_coupled.cfg' returned a non-zero code: 255

**Comment by kunstrasenspringer** [comment]
Hi Alexander,
Sorry forgot to mention the versions:

OS: ubuntu 16.04
SU2-Version: 6.0.0
Calculix-Version: 2.13
preCICE-Version: 3 (current version on github)
SU2-adapter-Version: current github version
Calculix-adapter-Version: current github version
tutorial: current github version

I can confirm that the adapter versions corresponds to the SU2 and Calculix versions.

Further information to the dockerimage: 
I clone & download everything "fresh" from github or website, so everything is in the current version. Then i build everything accordingly and then simulate.

Since the data produced by the simulation is useable and looks correct, my current work-around is to exit with zero. The exact command would be as follows:

_ccx_preCICE -i flap -precice-participant Calculix & SU2_CFD euler_config_coupled.cfg; **exit 0**_

**Comment by arusch** [comment]
Thanks for the additional information. I will look into it as soon as possible.

Am 13.03.2018 um 16:23 schrieb kunstrasenspringer <notifications@github.com<mailto:notifications@github.com>>:


Hi Alexander,
Sorry forgot to mention the versions:

OS: ubuntu 16.04
SU2-Version: 6.0.0
Calculix-Version: 2.13
preCICE-Version: 3 (current version on github)
SU2-adapter-Version: current github version
Calculix-adapter-Version: current github version
tutorial: current github version

I can confirm that the adapter versions corresponds to the SU2 and Calculix versions.

Further information to the dockerimage:
I clone & download everything "fresh" from github or website, so everything is in the current version. Then i build everything accordingly and then simulate.

Since the data produced by the simulation is useable and looks correct, my current work-around is to exit with zero. The exact command would be as follows:

ccx_preCICE -i flap -precice-participant Calculix & SU2_CFD euler_config_coupled.cfg; exit 0

**Comment by arusch** [comment]
Hi,
I tried to reproduce the error (without dockers). For me this simulation (and others that I have tested) terminates without errors. There was, indeed, an issue with memory deallocation some time ago. However, the problem was fixed and the most recent version of the SU2 adapter should not suffer from this any longer (and, in fact, it does not on my machines).
The respective commit was ([57fab7c502c8dcd6bf9c19f38bfa7a560556328d](https://github.com/precice/su2-adapter/commit/57fab7c502c8dcd6bf9c19f38bfa7a560556328d)) on the 30th, Jan 2018.

Are you sure that your adapter version includes this patch? 
If so, did you change anything in the tutorial regarding the time stepping or the end time of the simulation or did you use it straight "out of the box"?

If all of that does not help in troubleshooting, at least I can assure you that all necessary result files are written (and they are valid) before this error ends your simulation. This is simply a memory deallocation problem when destroying the adapter objects after the simulation itself has already ended.

**Comment by MakisH** [comment]
This seems to appear randomly and we are currently trying to understand it.

As @Ccaccia73 observed, the problem only appears if CalculiX finalizes and exits before SU2 finalizes. If CalculiX waits (e.g. sleeps) before exiting, SU2 also exits successfully.

**Comment by MakisH** [comment]
I assume this will not be the case anymore with the rewritten adapter, which directly uses the Python wrapper of SU2. Please reopen if you experience it again.
